### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by loordgek** [MineMaarten/AdvancedMod#5]
i got a crash

https://github.com/loordgek/AdvancedMod/blob/testing/src/main/java/com/minemaarten/advancedmod/tileentity/TileEntitiyGenerator.java

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.minemaarten.advancedmod.tileentity.TileEntitiyGenerator.updateEntity(TileEntitiyGenerator.java:177)
	at net.minecraft.world.World.updateEntities(World.java:2160)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:515)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:703)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

how do i fix it?

**Comment by MineMaarten** [comment]
This is a basic java error. I should 'send you back to java school', but I'm too nice:

Java is 0-based, arrays will start counting from 0 and up. So to get your first element, do GeneratorItemStacks[0].
